### ISSUE TITLE
Do we really need a ratatui frontend?

### ISSUE THREAD

**Issue by InnocentZero** [ripytide/pacdef#14]
I think the previous hand-rolled printing with the option to stop and apply till that point were good enough. I think adding Ratatui would just lead to more dependencies and IMO we should cut down on our dependencies a bit.  I don't even understand how we end up using upwards of 90 dependencies. In any case, if there are strong suggestions I'm open to implementation.

**Comment by ripytide** [comment]
I don't see the dependencies thing as much of an issue since a lot of the reason the old version had less dependencies is because it hand-rolled a lot of stuff which did mean fewer dependencies but often it meant maintaining a lot of odd unrelated code which was sometimes incorrect or buggier than it could be. Using more dependencies for niche functionality just seems like a better option overall imo since most dependencies have much more eyes on them for correctness etc.

Regarding pacdef review we don't necessarily need to go down the `ratarui` route, my main gripes were with the old system where it would take forever to do a review and there was no way to undo or save your progress of a review.

Perhaps an easier to implement but still nicer solution would be to export a big group file with all the unmanaged packages, the a user could manually copy the packages they wanted to keep into their real group files, then finally the user go do a pacdef remove-unmanaged or pacdef sync to remove the unwanted unmanaged packages?

**Comment by InnocentZero** [comment]
The last option seems pretty nice. Also, I think the newer review interface had an apply option that allowed you to stop and apply whatever options were done so far. So I think we can do either option. Honestly though, I'd like to have an interface, just not a very TUI one. They don't work well in ttys.

**Comment by ripytide** [comment]
Closing since I used the `metapac unmanaged > unmanaged.toml; nvim` method on my own system and it worked surprisingly well so I no longer see a need for us to provide a built-in review editor when any text editor can do just as good a job.
