### ISSUE TITLE
Should we deprecate pip?

### ISSUE THREAD

**Issue by InnocentZero** [ripytide/pacdef#9]
See [PEP 668](https://peps.python.org/pep-0668/) and [PyPA spec](https://packaging.python.org/en/latest/specifications/externally-managed-environments/)

This has been adopted by both Archlinux and Ubuntu 24.04. Maybe it makes sense to deprecate pip since it creates problems for natively installed packages anyways.

**Comment by ripytide** [comment]
From what I am getting from skimming those specs it looks to me as if pip itself is not being deprecated for manual installs of python, only package manager controlled installs, so would pip not still be a useful backend for those manual install users?

**Comment by InnocentZero** [comment]
The specification states that pip should exit should the libraries be 
1. Not in a venv
2. Managed by an external package manager

The usecase for our tool is basically both of them together. Makes no sense to keep pip considering it only creates more problems.

In any case, we can come up with a config option of `enable_global_pip` and set it to false by default.

**Comment by ripytide** [comment]
Why not simply let users try and fail to use the `pip` backend since on managed or non-venv environments `pip` should exit with a error message which will then be given to the user even when using `pacdef` as an intermediary?

I think we should be trying to be a transparent as possible (like a backend command translator) rather than taking stances on which backends should be used in which scenarios as that could be highly specific to the environment in which a user uses `pacdef`, like from within a venv for example.

**Comment by InnocentZero** [comment]
That's an interesting take. Sure, but the we definitely need to mention it somewhere in the README and allow `disabled_backends` in the config.
